import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import { syncUserDB } from './lib/auth/usersync'
import './globals.css'
import { Prisma } from '@prisma/client'
import { GetExerciseList } from './lib/queries/exercises'
import ExerciseList from '@/components/ExerciseList/ExerciseList'
import { ExerciseListItemType } from './lib/types/Exercise'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await syncUserDB();
  let exercises;

  if (user?.id) {
    exercises = await GetExerciseList(user?.id);
    console.log(exercises);
  }


  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <div style={{ width: 'fit-content', margin: '0 auto' }}>
                <UserButton />
                <p>Your are so cool</p>

              </div>
            </SignedIn>
          </header>
          {exercises && < ExerciseList exercises={exercises} />}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
