import { type Metadata } from 'next'
import {
  ClerkProvider
} from '@clerk/nextjs'
import TopNav from '@/components/TopNav';
import { Geist, Geist_Mono } from 'next/font/google'
import Container from '@/components/Container';
import { syncUserDB } from './lib/auth/usersync'
import './globals.css'
import { GetExerciseList } from './lib/queries/exercises'
import ExerciseList from '@/components/ExerciseList/ExerciseList'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={` dark ${geistSans.variable} ${geistMono.variable} antialiased`}>
          <TopNav />
          <Container>
            {children}
          </Container>
        </body>
      </html>
    </ClerkProvider>
  )
}
